# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from Adafruit_IO import MQTTClient
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon

# Set to your Adafruit IO key.
# Remember, your key is a secret,
# so make sure not to publish it when you publish this code!
ADAFRUIT_IO_KEY = '846e3070c6f144efa0d3b62d5b583775'

# Set to your Adafruit IO username.
# (go to https://accounts.adafruit.com to find your username)
ADAFRUIT_IO_USERNAME = 'chota_scientists'

TEMPERATURE = 'temprature'  # topic for temperature
HUMIDITY = 'humidity'  # topic for humidity
v = 'voltage'
CURRENT = 'current'
OIL = 'oil'
VIBRATION = 'vibration'
BODY = 'relay1'


# Define callback functions which will be called when certain events happen.
def connected(client):
    """Connected function will be called when the client is connected to
    Adafruit IO.This is a good place to subscribe to feed changes.  The client
    parameter passed to this function is the Adafruit IO MQTT client so you
    can make calls against it easily.
    """
    # Subscribe to changes on a feed named Counter.
    ui.ClicktoConnect.setText("Connecting to the server...")
    print('Subscribing to Feed {0}'.format(TEMPERATURE))
    client.subscribe(TEMPERATURE)
    print('Subscribing to Feed {0}'.format(HUMIDITY))
    client.subscribe(HUMIDITY)
    print('Subscribing to Feed {0}'.format(v))
    client.subscribe(v)
    print('Subscribing to Feed {0}'.format(CURRENT))
    client.subscribe(CURRENT)
    print('Subscribing to Feed {0}'.format(OIL))
    client.subscribe(OIL)
    print('Subscribing to Feed {0}'.format(VIBRATION))
    client.subscribe(VIBRATION)
    print('Subscribing to Feed {0}'.format(BODY))
    client.subscribe(BODY)
    ui.ClicktoConnect.setText("        Loading Data ")


def disconnected(client):
    """Disconnected function will be called when the client disconnects."""
    ui.ConnectButton.setText("Disconnected")
    # sys.exit(1)


class Ui_dtf(object):
    def setupUi(self, dtf):
        data = 0
        dtf.setObjectName("dtf")
        dtf.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dtf.setWindowIcon(QIcon("./logo.ico"))
        dtf.resize(617, 296)
        dtf.setMinimumSize(QtCore.QSize(617, 296))
        dtf.setMaximumSize(QtCore.QSize(617, 296))
        self.MainHeadline = QtWidgets.QLabel(dtf)
        self.MainHeadline.setGeometry(QtCore.QRect(80, 11, 471, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.MainHeadline.setFont(font)
        self.MainHeadline.setObjectName("MainHeadline")
        self.layoutWidget = QtWidgets.QWidget(dtf)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 62, 531, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Voltag_head_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Voltag_head_2.setFont(font)
        self.Voltag_head_2.setObjectName("Voltag_head_2")
        self.horizontalLayout_5.addWidget(self.Voltag_head_2)
        self.voltage_label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.voltage_label_2.setFont(font)
        self.voltage_label_2.setText("")
        self.voltage_label_2.setObjectName("voltage_label_2")
        self.horizontalLayout_5.addWidget(self.voltage_label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Temp_head = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Temp_head.setFont(font)
        self.Temp_head.setObjectName("Temp_head")
        self.horizontalLayout_6.addWidget(self.Temp_head)
        self.temp_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.temp_label.setFont(font)
        self.temp_label.setText("")
        self.temp_label.setObjectName("temp_label")
        self.horizontalLayout_6.addWidget(self.temp_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.oil_head = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.oil_head.setFont(font)
        self.oil_head.setObjectName("oil_head")
        self.horizontalLayout_8.addWidget(self.oil_head)
        self.oil_lable = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.oil_lable.setFont(font)
        self.oil_lable.setText("")
        self.oil_lable.setObjectName("oil_lable")
        self.horizontalLayout_8.addWidget(self.oil_lable)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Current_head = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Current_head.setFont(font)
        self.Current_head.setObjectName("Current_head")
        self.horizontalLayout_3.addWidget(self.Current_head)
        self.Current_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Current_label.setFont(font)
        self.Current_label.setText("")
        self.Current_label.setObjectName("Current_label")
        self.horizontalLayout_3.addWidget(self.Current_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Humi_head = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Humi_head.setFont(font)
        self.Humi_head.setObjectName("Humi_head")
        self.horizontalLayout_2.addWidget(self.Humi_head)
        self.humidity_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.humidity_label.setFont(font)
        self.humidity_label.setText("")
        self.humidity_label.setObjectName("humidity_label")
        self.horizontalLayout_2.addWidget(self.humidity_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vibration_head = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vibration_head.setFont(font)
        self.vibration_head.setObjectName("vibration_head")
        self.horizontalLayout.addWidget(self.vibration_head)
        self.vibration_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vibration_label.setFont(font)
        self.vibration_label.setText("")
        self.vibration_label.setObjectName("vibration_label")
        self.horizontalLayout.addWidget(self.vibration_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.ClicktoConnect = QtWidgets.QLabel(dtf)
        self.ClicktoConnect.setGeometry(QtCore.QRect(80, 219, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ClicktoConnect.setFont(font)
        self.ClicktoConnect.setObjectName("ClicktoConnect")

        self.ConnectButton = QtWidgets.QPushButton(dtf)
        self.ConnectButton.setGeometry(QtCore.QRect(100, 239, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ConnectButton.setFont(font)
        self.ConnectButton.setObjectName("ConnectButton")
        self.ConnectButton.clicked.connect(self.connect_clicked)
        self.body_temp_label = QtWidgets.QLabel(dtf)
        self.body_temp_label.setGeometry(QtCore.QRect(240, 170, 126, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.body_temp_label.setFont(font)
        self.body_temp_label.setText("")
        self.body_temp_label.setObjectName("body_temp_label")
        self.body_temp_head = QtWidgets.QLabel(dtf)
        self.body_temp_head.setGeometry(QtCore.QRect(40, 170, 201, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.body_temp_head.setFont(font)
        self.body_temp_head.setObjectName("body_temp_head")
        self.load_heading = QtWidgets.QLabel(dtf)
        self.load_heading.setGeometry(QtCore.QRect(413, 220, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.load_heading.setFont(font)
        self.load_heading.setObjectName("load_heading")
        self.load_buttun_on = QtWidgets.QPushButton(dtf)
        self.load_buttun_on.setGeometry(QtCore.QRect(400, 240, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.load_buttun_on.setFont(font)
        self.load_buttun_on.setObjectName("load_buttun_on")
        self.load_buttun_on.clicked.connect(self.on_clicked)
        self.load_buttun_off = QtWidgets.QPushButton(dtf)
        self.load_buttun_off.setGeometry(QtCore.QRect(480, 240, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.load_buttun_off.setFont(font)
        self.load_buttun_off.setObjectName("load_buttun_off")
        self.load_buttun_off.clicked.connect(self.off_clicked)
        self.retranslateUi(dtf)
        QtCore.QMetaObject.connectSlotsByName(dtf)

    def retranslateUi(self, dtf):
        _translate = QtCore.QCoreApplication.translate
        dtf.setWindowTitle(_translate("dtf", "Dashboard"))
        self.MainHeadline.setText(_translate("dtf", "Distrubution Transformer Monitoring Dashboard"))
        self.Voltag_head_2.setText(_translate("dtf", "Voltage :"))
        self.Temp_head.setText(_translate("dtf", "Temperature :"))
        self.oil_head.setText(_translate("dtf", "Oil Level :"))
        self.Current_head.setText(_translate("dtf", "Current :"))
        self.Humi_head.setText(_translate("dtf", "Humidity :"))
        self.vibration_head.setText(_translate("dtf", "Vibration :"))
        self.ClicktoConnect.setText(_translate("dtf", "Click to Connect Device"))
        self.ConnectButton.setText(_translate("dtf", "Connect "))
        self.body_temp_head.setText(_translate("dtf", "Transformer Temperature :"))
        self.load_heading.setText(_translate("dtf", "Click to Connect the Load"))
        self.load_buttun_on.setText(_translate("dtf", "On"))
        self.load_buttun_off.setText(_translate("dtf", "Off"))

    def connect_clicked(self, Dashboard):
        _translate = QtCore.QCoreApplication.translate
        self.ConnectButton.setText(_translate("dtf", "Connected "))
        self.ClicktoConnect.setText(_translate("dtf", "Wait for few Seconds"))
        client.connect(keepalive=60)
        client.loop_background()

    def on_clicked(self, Dashboard):
        global data
        _translate = QtCore.QCoreApplication.translate
        self.load_heading.setText(_translate("dtf", "Load Connected "))
        # client.publish("relay2", payload="1", qos=0)
        # client.publish("relay2","0")
        data = 1
        print("data value: " + str(data))


    def off_clicked(self, Dashboard):
        global data
        _translate = QtCore.QCoreApplication.translate
        self.load_heading.setText(_translate("dtf", " Load Dissconnected"))
        # client.publish("relay2", payload="1", qos=0)
        # client.publish("relay2", "1")
        data = 0
        print("data value: " + str(data))



def message(client, feed_id, payload):
    """Message function will be called when a subscribed feed has a new value.
    The feed_id parameter identifies the feed, and the payload parameter has
    the new value.
    """
    ui.ClicktoConnect.setText("")
    if feed_id == TEMPERATURE:
        print(payload)
        ui.temp_label.setText(payload + " °C")

    if feed_id == HUMIDITY:
        print(payload)
        ui.humidity_label.setText(payload + " %")

    if feed_id == OIL:
        print(payload)
        ui.oil_lable.setText(payload + " %")

    if feed_id == v:
        print(payload)
        ui.voltage_label_2.setText(payload + " Volts")

    if feed_id == CURRENT:
        print(payload)
        ui.Current_label.setText(payload + " Amps")

    if feed_id == VIBRATION:
        if int(payload) >= 100:
            print("Slight Movement")
            ui.vibration_label.setText("Slight Vibration")
        else:
            print("Stable")
            ui.vibration_label.setText("Stable")

    if feed_id == BODY:
        print("body : " + payload)
        ui.body_temp_label.setText(payload + "°C ")
    global data
    if data == 1:
        client.publish("relay2", "0")
        print("onn")
    else:
        client.publish("relay2", "1")
        print("off")




# Create an MQTT client instance.
client = MQTTClient(ADAFRUIT_IO_USERNAME, ADAFRUIT_IO_KEY)
# Setup the callback functions defined above.
client.on_connect = connected
client.on_disconnect = disconnected
client.on_message = message

# Connect to the Adafruit IO server.


if __name__ == "__main__":
    import sys
    data = 0
    app = QtWidgets.QApplication(sys.argv)
    Registration = QtWidgets.QWidget()
    ui = Ui_dtf()
    ui.setupUi(Registration)
    Registration.show()
    sys.exit(app.exec())
