# Form implementation generated from reading ui file 'new_format.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_transformer(object):
    def setupUi(self, transformer):
        transformer.setObjectName("transformer")
        transformer.resize(649, 318)
        transformer.setMinimumSize(QtCore.QSize(649, 318))
        transformer.setMaximumSize(QtCore.QSize(649, 318))
        self.headline = QtWidgets.QLabel(transformer)
        self.headline.setGeometry(QtCore.QRect(100, 10, 451, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.headline.setFont(font)
        self.headline.setObjectName("headline")

        self.retranslateUi(transformer)
        QtCore.QMetaObject.connectSlotsByName(transformer)

    def retranslateUi(self, transformer):
        _translate = QtCore.QCoreApplication.translate
        transformer.setWindowTitle(_translate("transformer", "Form"))
        self.headline.setText(_translate("transformer", "Distribution Transformer Monitoring System"))
